version: '3.8'
services:
  jwt_db:
    image: postgres:15-alpine
    container_name: jwt_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: jwt_security
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: 123test
    ports:
      - "5432:5432"
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U docker -d jwt_security' ]
      interval: 120s
      timeout: 5s
      retries: 5
      start_period: 10s
